// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

public enum ModuleState : byte
{
  NONE = 0,
  MotorState = 1,
};



static public class ModuleStateVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((ModuleState)typeId)
    {
      case ModuleState.MotorState:
        result = MotorStateVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}

