// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

public enum ModuleType : sbyte
{
  SPLITTER = 0,
  SERVO_1 = 1,
  DC_MOTOR = 2,
  BATTERY = 3,
  SERVO_2 = 4,
};

