// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

public enum Orientation : sbyte
{
  Deg0 = 0,
  Deg90 = 1,
  Deg180 = 2,
  Deg270 = 3,
};

